spring.mongodb.uri=mongodb://localhost:27017/restaurant_db
server.port=8080
OPENAI_API_KEY=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